console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  blue = '#114FCC'
  gray = '#cccccc'
  green = '#59C9A5'
  lightBlue = '#8df9fd'
  lightGreen = '#b2e052'
  orange = '#F07623'
  paleGreen = '#87ffaf'
  purple = '#a47ce8'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[transient_prompt]
  template = ' '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = '<green>╭─</> {{ .Path }} '
    foreground = 'p:lightBlue'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{end}} '
    foreground = 'p:white'
    background = 'transparent'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .Full }} '
    foreground = 'p:lightGreen'
    type = 'node'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ if .Error }}{{ .Error }}{{ else }} 󰧦 {{ .Major }}.{{ .Minor }}{{ end }}'
    foreground = 'p:purple'
    type = 'php'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      style = 'round'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '╰─'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']
